export enum JobApplicationStatus {
    APPLIED = "APPLIED",
    REVIEW = "REVIEW",
    REJECTED = "REJECTED",
    APPROVED = "APPROVED",
    SHORTLISTED = "SHORTLISTED",
    INTERVIEW = "INTERVIEW",
    HIRED = "HIRED"
}

export const APPLICATION_QUEUE_ID = 'APPLICATION_QUEUE_ID'